name: Go

on:
  push:
    branches: [ "master" ]

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Stop app    
      run: sudo systemctl stop hppApp.service

    - name: Delete old binaries
      run: sudo rm -rf hppGacha

    - name: Build
      run: sudo -E go build

    - name: Copy
      run: sudo cp -fr . /home/ubuntu/hppApp

    - name: Launch app
      run: sudo systemctl restart hppApp.service
